### ISSUE TITLE
Validating calculations for moments?

### ISSUE THREAD

**Issue by jennykim1016** [LSSTDESC/SLRealizer#16]
I checked my moment calculations through plotting lensed systems and plotting the center of flux in jupyter notebook. I used both the zeroth and the first moment to do this. I found few bugs while doing this, but they are all fixed.

The problem I have right now is that this way of checking does not seem rigorous enough. Python's unit test, I think, is not a good way to check the results in this case. All the zeroth, first, and second moments involve log or power of 2.5, and all the values differ for a small amount(most of the values range from zero to one so rounding up to use `assertequal` would not give useful information).

Would there be any better way to test the codes that I wrote? Thanks!

**Comment by rbiswas4** [comment]
Within the usual python world, you can use `numpy.testing`  asserts (for example: https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_almost_equal.html) 
which allow you to specify  the precision (in some cases either in absolute or relative terms), and as a bonus can act on arrays rather than having to iterate the tests through arrays. You can also build upon these to have more details in these methods. The LSST stack has some more detailed methods, but then you have to depend on it.

**Comment by jennykim1016** [comment]
Oh, I did not know there was `assert almost equal` method. Thank you so much! Should I then just calculate the moments with a pen and paper(using calculators), write unit tests, and see whether the reported values are approximately equal to the values that I get for 0th, 1st, and 2nd moments?

**Comment by drphilmarshall** [comment]
This is a good idea for a unit test. Thanks for starting the [tests](https://github.com/LSSTDESC/SLRealizer/blob/master/tests/test_SLRealizer.py) file!
